upstream backend {
    server backend:8080;
}

upstream frontend {
    server frontend:80;
}

server {
    listen 80;
    server_name _;

    location /api/ {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://backend/api/;
    }

    location /v3/api-docs {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://backend/v3/api-docs;
    }

    location /swagger-ui.html {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://backend/swagger-ui.html;
    }

    location /swagger-ui/ {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://backend/swagger-ui/;
    }

    location /webjars/ {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://backend/webjars/;
    }

    location / {
        include /etc/nginx/conf.available/proxy-common.conf;
        proxy_pass http://frontend/;
    }
}
