spring.application.name=crypto

server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crypto_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

crypto.keystore.path=keystore/crypto-service.p12
crypto.keystore.password=${CRYPTO_KEYSTORE_PASSWORD:my-strong-password}
crypto.keystore.alias=crypto-service
crypto.keystore.key-size=2048

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
